# Generated by Django 3.2 on 2021-09-24 10:49

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0004_auto_20210423_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Products_Name', models.CharField(max_length=100)),
                ('Code', models.IntegerField(unique=True)),
                ('Product_Description', models.TextField(default='')),
                ('Products_Attachment', models.FileField(default='', upload_to='file')),
                ('Products_Image', models.ImageField(default='', upload_to='images')),
                ('Products_Type', models.CharField(choices=[('our products', 'Our Products'), ('product-industry', 'Product-Industry')], default='', max_length=100)),
                ('Products_Category', models.CharField(choices=[('Our Products', (('agar_plates', 'Agar Plates'), ('bi_agar_plates_90mm', 'Bi Agar Plates 90mm'), ('agar_plates_150mm', 'Agar Plates 150mm'), ('tubed_media', 'Tubed Media'), ('bottled_media', 'Bottled Media'), ('blood_products', 'Blood Products'), ('antibiotic_discs', 'Antibiotic Discs'), ('aTCC-Microbiologic', 'ATCC-Microbiologic'), ('petroleum', 'Petroleum'))), ('Product-Industry', (('clinical', 'Clinical'), ('cosmetic', 'Cosmetic'), ('dairy', 'Dairy'), ('food', 'Food & Beverage'), ('veterinary', 'Veterinary'), ('Water_Wastewater', 'Water & Wastewater'))), ('unknown', 'Unknown')], default='', max_length=100)),
                ('slug', models.SlugField(default='', help_text='Products Category and slug are must be same.')),
                ('Indended_Use', taggit.managers.TaggableManager(help_text='Tag', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('Code',),
            },
        ),
        migrations.CreateModel(
            name='QCCertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch', models.IntegerField()),
                ('Plant', models.CharField(max_length=50)),
                ('Products_Attachment', models.FileField(default='', upload_to='QCCertificates/file')),
                ('Expiry_date', models.DateField()),
                ('Products_Name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'verbose_name': 'QC Certificate',
                'verbose_name_plural': 'QC Certificates',
            },
        ),
    ]
